#! /usr/bin/env python3
#
# T. Inagaki
#
"""
  USAGE:
    interactive:
    anadisp

    options:
    anadisp --server=cda01 --oaccount=o19011 --passwordfile='/tmp/passwordfile.txt'

  IMPORTANT NOTE:
    You need Tiger VNC viewer installed to use this program, and it needs to be in your $PATH
"""
import sys
import os
import getpass
from argparse import ArgumentParser


def main(options, args):

    if options.server:
        aserver = options.server
    else:
        sys.stdout.write("analysis server[sumda|cda01|cda02|mtkda]: ")
        sys.stdout.flush()
        aserver = sys.stdin.readline()
        aserver = aserver.strip()

    if options.oaccount:
        oacct = options.oaccount
    else:
        sys.stdout.write("o-account: ")
        sys.stdout.flush()
        oacct = sys.stdin.readline()
        oacct = oacct.strip()

    if options.passwordfile:
        with open(options.passwordfile) as fp:
            opass = fp.readline()
            opass = opass.strip()
    else:
        opass = getpass.getpass("o-password: ")
        opass = opass.strip()

    adisp = int(oacct[1:])

    passfile = os.path.join(os.environ['HOME'], '.__vp')
    cmdstr = "echo '{}' | vncpasswd -f > {}".format(opass, passfile)
    res = os.system(cmdstr)

    cmdstr = "chmod go-rwx {}".format(passfile)
    res = os.system(cmdstr)

    cmdstr = "vncviewer {}:{} -Shared -passwd {} &".format(aserver, adisp, passfile)
    res = os.system(cmdstr)


if __name__ == '__main__':

    argprs = ArgumentParser(description="Display an ANA VNC session")

    argprs.add_argument("--oaccount", dest="oaccount", metavar="OACCOUNT",
                        help="Specify o-account")

    argprs.add_argument("--passwordfile", dest="passwordfile",
                        metavar="PASSWORDFIULE",
                        default=False,
                        help="Specify password file")

    argprs.add_argument("--server", dest="server", metavar="SERVER",
                        help="Specify analisys server")

    (options, args) = argprs.parse_known_args(sys.argv[1:])

    main(options, args)
