#! /usr/bin/env python
#

import sys
from argparse import ArgumentParser

from g2base import ssdlog
from g2ana.ana import main


if __name__ == "__main__":

    # Parse command line options
    argprs = ArgumentParser(description="Start up the analysis menu.")

    argprs.add_argument("--debug", dest="debug", default=False,
                        action="store_true",
                        help="Enter the pdb debugger on main()")

    argprs.add_argument("--rohost", dest="rohost", metavar="ROHOST",
                        default="localhost",
                        help="Specify rohost")

    argprs.add_argument("--geometry", dest="geometry",
                        default="+100+100",
                        help="Specify placement of window")

    argprs.add_argument("--profile", dest="profile", action="store_true",
                        default=False,
                        help="Run the profiler on main()")
    ssdlog.addlogopts(argprs)

    (options, args) = argprs.parse_known_args(sys.argv[1:])

    if len(args) != 1:
        argprs.error("incorrect number of arguments")

    # Are we debugging this?
    if options.debug:
        import pdb

        pdb.run('main(options, args)')

    # Are we profiling this?
    elif options.profile:
        import profile

        print("%s profile:" % sys.argv[0])
        profile.run('main(options, args)')

    else:
        main(options, args)
