#! /usr/bin/env python
#

import sys
from optparse import OptionParser

from g2base import ssdlog
from g2ana.ana import main


if __name__ == "__main__":

    # Parse command line options

    usage = "usage: %prog [options] [file] ..."
    optprs = OptionParser(usage=usage, version=('%prog'))


    optprs.add_option("--debug", dest="debug", default=False,
                      action="store_true",
                      help="Enter the pdb debugger on main()")

    optprs.add_option("--rohost", dest="rohost", metavar="ROHOST",
                      default="localhost",
                      help="Specify rohost")

    optprs.add_option("--geometry", dest="geometry", 
                      default="+100+100",
                      help="Specify placement of window")

    optprs.add_option("--profile", dest="profile", action="store_true",
                      default=False,
                      help="Run the profiler on main()")
    ssdlog.addlogopts(optprs)

    (options, args) = optprs.parse_args(sys.argv[1:])

    if len(args) != 1:
        optprs.error("incorrect number of arguments")

    # Are we debugging this?
    if options.debug:
        import pdb

        pdb.run('main(options, args)')

    # Are we profiling this?
    elif options.profile:
        import profile

        print("%s profile:" % sys.argv[0])
        profile.run('main(options, args)')

    else:
        main(options, args)
