#!/usr/bin/env python

import sys
from argparse import ArgumentParser

from g2base import ssdlog
from g2ana.cleanup_fits import main


if __name__ == '__main__':

    # Parse command line options
    argprs = ArgumentParser(description="Cleanup old FITS files")

    argprs.add_argument('-d', "--fitsdir", dest="fitsdir", metavar="DIR",
                        default=None,
                        help="Use DIR for storing instrument FITS files")
    argprs.add_argument("--daemon", dest="daemon",  action="store_true",
                        default=False,
                        help="Run as a daemon.")
    argprs.add_argument("--dry-run", dest="dry_run", default=False,
                        action="store_true",
                        help="Don't really delete files, just show what we would do")
    argprs.add_argument("--hi", dest="hiwater", metavar="PCT",
                        type=int, default=80,
                        help="Set high water disk usage to PCT")
    argprs.add_argument("--interval", dest="interval", metavar="SECS",
                        type=float, default=60.0,
                        help="Set interval for waiting between disk checks")
    argprs.add_argument("--lo", dest="lowater", metavar="PCT",
                        type=int, default=40,
                        help="Set low water disk usage to PCT")
    ssdlog.addlogopts(argprs)

    (options, args) = argprs.parse_known_args(sys.argv[1:])

    if len(args) > 0:
       argprs.error("incorrect number of arguments")

    main(options, args)
